name: relogio_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/sounds/timer_end.mp3
    - assets/fonts/

  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/Digital-7.ttf
